In [1]:
import numpy as np

In [14]:
class Network:
    def __init__(self, layers):
        self.network = {}
        self.layers = layers
        
        for i in range(1, len(layers)):
            self.network[f"layer {i}"] = {
                "weights" : np.random.rand(
                        layers[i - 1],     # per each row each output
                        layers[i]          # per each col each input
                    ),
                "bias" : np.random.rand(
                        layers[i]
                    )
                                 
            }
    
    def activation(self, values):
        """
            sigmoid activation function
        """
        sigmoid = lambda x : 1 / (1 + np.exp(-x))
        
        return np.array([
            sigmoid(value) for value in values
        ])
        
    def forward(self, input_layer):
        """
            outcome function which will give the output values output layer
            
            
            output = f(w.transpose * input + bias)
        """
        input_values = np.array(input_layer)
        
        for layer_name, layer in self.network.items():
            print(f"\n {layer_name} weights :", layer["weights"])
            print(f"\n {layer_name} bias :", layer["bias"])
            layer_output = (layer['weights'].transpose() @ input_values) + layer['bias']
            #print(f"\n {layer_name} Output :", layer_output)
            threshold_output = self.activation(layer_output)
            #print(f"\n {layer_name} Threshold_Output :", threshold_output)
            input_values = threshold_output
            
        return np.round(input_values, 2)

In [15]:
network = Network([5, 3, 2, 3, 1])
print(f"\n Final Output is {network.forward([2, 1,1,1,2])}")


 layer 1 weights : [[0.26948949 0.10415857 0.90070736]
 [0.257215   0.57089685 0.96685542]
 [0.12942828 0.29031081 0.77736546]
 [0.57253836 0.43271755 0.24256268]
 [0.61440176 0.23980449 0.31959126]]

 layer 1 bias : [0.54194751 0.62816686 0.52531117]

 layer 2 weights : [[0.72731696 0.61219216]
 [0.84880469 0.39726388]
 [0.85292373 0.78300642]]

 layer 2 bias : [0.97232901 0.66011998]

 layer 3 weights : [[0.10793389 0.45145061 0.63541448]
 [0.04048373 0.17408359 0.70521273]]

 layer 3 bias : [0.63770516 0.28852351 0.54822281]

 layer 4 weights : [[0.51978933]
 [0.34667916]
 [0.57375955]]

 layer 4 bias : [0.44386095]

 Final Output is [0.82]
