In [7]:
import numpy as np

In [8]:
class Network:
    def __init__(self, layers):
        self.network = {}
        self.layers = layers
        
        for i in range(1, len(layers)):
            self.network[f"layer {i}"] = {
                "weights" : np.random.rand(
                layers[i-1], 
                layers[i]),
                "bias" : np.random.rand(
                layers[i])
            }
            
        
    def activation(self, values):
        """
            RELU activation function
        """
        relu = lambda x : max(0, x)
        
        return np.array([
            relu(value) for value in values
        ])
    
    def forward(self, input_layer):
        """
            outcome function which will give the output values output layer
            
            
            output = f(w.transpose * input + bias)
        """
        input_values = np.array(input_layer)
        #print("dimensions",input_values)
        for layer_name, layer in self.network.items():
            print(f"\n {layer_name} weights :", np.round(layer["weights"],2))
            print(f"\n {layer_name} bias :", np.round(layer["bias"],2))
            layer_output =np.round((layer['weights'].transpose() @ input_values) + layer['bias'],2)
            print(f"\n {layer_name} Weighted sum :", layer_output)
            threshold_output = np.round(self.activation(layer_output),2)
            print(f"\n {layer_name} Threshold_Output :", threshold_output)
            input_values = threshold_output
            
        return np.round(input_values, 2)
    

In [9]:
network = Network([5, 3, 2, 3, 1])
print(f"\nOutput is {network.forward([2, 1, 1 , 1, 2])}")


 layer 1 weights : [[0.22 0.56 0.53]
 [0.22 0.42 0.8 ]
 [0.09 0.05 0.04]
 [0.62 0.04 0.11]
 [0.31 0.42 0.15]]

 layer 1 bias : [0.96 0.77 0.46]

 layer 1 Weighted sum : [2.95 3.25 2.76]

 layer 1 Threshold_Output : [2.95 3.25 2.76]

 layer 2 weights : [[0.34 0.35]
 [0.58 0.73]
 [0.16 0.47]]

 layer 2 bias : [0.31 0.2 ]

 layer 2 Weighted sum : [3.65 4.9 ]

 layer 2 Threshold_Output : [3.65 4.9 ]

 layer 3 weights : [[0.48 0.42 0.76]
 [0.02 0.28 0.86]]

 layer 3 bias : [0.54 0.33 0.38]

 layer 3 Weighted sum : [2.4  3.23 7.36]

 layer 3 Threshold_Output : [2.4  3.23 7.36]

 layer 4 weights : [[0.96]
 [0.73]
 [0.97]]

 layer 4 bias : [0.41]

 layer 4 Weighted sum : [12.22]

 layer 4 Threshold_Output : [12.22]

Output is [12.22]
