In [1]:
import numpy as np

In [6]:
class Network:
    def __init__(self, layers):
        self.network = {}
        self.layers =  layers
        
        for i in range(1, len(layers)):
            self.network[f"layer {i}"] = {
                "weights" : np.random.rand(
                layers[i-1],
                layers[i]),
                "bias" : np.random.rand(
                layers[i])
            }
            
    def activation(self, values):
        """
            tanh activation function
        """
        tanh = lambda x : (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))
        
        return np.array(
            list(
                map(
                    tanh, 
                    values.tolist()
                )
            ), 
            dtype='float32'
        )
        
    def forward(self, input_layer):
        """
            outcome function which will give the output values output layer
            
            
            output = f(w.transpose * input + bias)
        """
        input_values = np.array(input_layer)
        #print("dimensions",input_values)
        for layer_name, layer in self.network.items():
            print(f"\n {layer_name} weights :", np.round(layer["weights"],2))
            print(f"\n {layer_name} bias :", np.round(layer["bias"],2))
            layer_output =np.round((layer['weights'].transpose() @ input_values) + layer['bias'],2)
            print(f"\n {layer_name} Weighted sum :", layer_output)
            threshold_output = np.round(self.activation(layer_output),2)
            print(f"\n {layer_name} Threshold_Output :", threshold_output)
            input_values = threshold_output
            
        return np.round(input_values, 2)

In [7]:
network = Network([5, 3, 2, 3, 1])
print(f"\n Final Output is {network.forward([2, 1,1,1,2])}")


 layer 1 weights : [[0.34 0.58 0.97]
 [0.04 0.9  0.14]
 [0.3  0.27 0.8 ]
 [0.75 0.83 0.06]
 [0.21 0.39 0.29]]

 layer 1 bias : [0.75 0.45 0.46]

 layer 1 Weighted sum : [2.95 4.39 3.99]

 layer 1 Threshold_Output : [0.99 1.   1.  ]

 layer 2 weights : [[0.92 0.44]
 [0.79 0.4 ]
 [0.22 0.31]]

 layer 2 bias : [0.18 0.46]

 layer 2 Weighted sum : [2.1 1.6]

 layer 2 Threshold_Output : [0.97 0.92]

 layer 3 weights : [[0.72 0.07 0.5 ]
 [0.68 0.52 0.62]]

 layer 3 bias : [0.77 0.96 0.71]

 layer 3 Weighted sum : [2.09 1.51 1.76]

 layer 3 Threshold_Output : [0.97 0.91 0.94]

 layer 4 weights : [[0.28]
 [0.86]
 [0.74]]

 layer 4 bias : [0.01]

 layer 4 Weighted sum : [1.76]

 layer 4 Threshold_Output : [0.94]

 Final Output is [0.94]
