In [1]:
import numpy as np

In [2]:
class Network:
    def __init__(self, layers):
        self.network = {}
        self.layers = layers
        
        for i in range(1, len(layers)):
            self.network[f"layer {i}"] = {
                "weights" : np.random.rand(
                        layers[i - 1],     # per each row each output
                        layers[i]          # per each col each input
                    ),
                "bias" : np.random.rand(
                        layers[i]
                    )
                                 
            }
    
    def activation(self, values):
        """
            sigmoid activation function
        """
        sigmoid = lambda x : 1 / (1 + np.exp(-x))
        
        return np.array([
            sigmoid(value) for value in values
        ])
        
    def forward(self, input_layer):
        """
            outcome function which will give the output values output layer
            
            
            output = f(w.transpose * input + bias)
        """
        input_values = np.array(input_layer)
        #print("dimensions",input_values)
        for layer_name, layer in self.network.items():
            print(f"\n {layer_name} weights :", np.round(layer["weights"],2))
            print(f"\n {layer_name} bias :", np.round(layer["bias"],2))
            layer_output =np.round((layer['weights'].transpose() @ input_values) + layer['bias'],2)
            print(f"\n {layer_name} Weighted sum :", layer_output)
            threshold_output = np.round(self.activation(layer_output),2)
            print(f"\n {layer_name} Threshold_Output :", threshold_output)
            input_values = threshold_output
            
        return np.round(input_values, 2)

In [3]:
network = Network([5, 3, 2, 3, 1])
print(f"\n Final Output is {network.forward([2, 1,1,1,2])}")


 layer 1 weights : [[0.88 0.41 0.25]
 [0.51 0.2  0.44]
 [0.09 0.51 0.56]
 [0.2  0.45 0.07]
 [0.61 0.92 0.88]]

 layer 1 bias : [0.19 0.64 0.93]

 layer 1 Weighted sum : [3.96 4.46 4.25]

 layer 1 Threshold_Output : [0.98 0.99 0.99]

 layer 2 weights : [[0.13 0.22]
 [0.88 0.52]
 [0.77 0.98]]

 layer 2 bias : [0.67 0.98]

 layer 2 Weighted sum : [2.43 2.69]

 layer 2 Threshold_Output : [0.92 0.94]

 layer 3 weights : [[0.65 0.12 0.22]
 [0.87 0.55 0.08]]

 layer 3 bias : [0.53 0.25 0.41]

 layer 3 Weighted sum : [1.95 0.88 0.69]

 layer 3 Threshold_Output : [0.88 0.71 0.67]

 layer 4 weights : [[0.02]
 [0.35]
 [0.87]]

 layer 4 bias : [0.71]

 layer 4 Weighted sum : [1.56]

 layer 4 Threshold_Output : [0.83]

 Final Output is [0.83]
