In [1]:
import numpy as np

In [2]:
class Network:
    def __init__(self, layers):
        self.network = {}
        self.layers =  layers
        
        for i in range(1, len(layers)):
            self.network[f"layer {i}"] = {
                "weights" : np.random.rand(
                layers[i-1],
                layers[i]),
                "bias" : np.random.rand(
                layers[i])
            }
            
    def activation_function(self, values):
        """
            tanh activation function
        """
        tanh = lambda x : (np.exp(-x) - np.exp(x)) / (np.exp(-x) + np.exp(x))
        
        return np.array(
            list(
                map(
                    tanh, 
                    values.tolist()
                )
            ), 
            dtype='float32'
        )
        
    def forward(self, input_layer):
        """
            outcome function which will give the output values output layer
            
            
            output = f(w.transpose * input + bias)
        """
        input_values = np.array(input_layer)
        
        for layer_name, layer in self.network.items():
            print(f"\n {layer_name} weights :", layer["weights"])
            print(f"\n {layer_name} bias :", layer["bias"])
            layer_output = (layer['weights'].transpose() @ input_values) + layer['bias']
            #print(f"\n {layer_name} Output :", layer_output)
            threshold_output = self.activation_function(layer_output)
            #print(f"\n {layer_name} Threshold_Output :", threshold_output)
            input_values = threshold_output
            
        return np.round(input_values, 2)

In [4]:
network = Network([5, 3, 2, 3, 1])
print(f"\n Final Output is {network.forward([2, 1,1,1,2])}")


 layer 1 weights : [[0.32564396 0.28926181 0.07626392]
 [0.64149179 0.10313758 0.25834476]
 [0.07537695 0.9242185  0.83244987]
 [0.4777499  0.90831051 0.95947614]
 [0.49936886 0.8993287  0.71131695]]

 layer 1 bias : [0.86556557 0.29322153 0.43284446]

 layer 2 weights : [[0.8521238  0.15530767]
 [0.50685951 0.9836112 ]
 [0.99242068 0.68886785]]

 layer 2 bias : [0.90307847 0.49762261]

 layer 3 weights : [[0.66048538 0.89477574 0.29728703]
 [0.20615474 0.68467219 0.48926699]]

 layer 3 bias : [0.73943037 0.24327108 0.96626442]

 layer 4 weights : [[0.69925018]
 [0.73591995]
 [0.57535177]]

 layer 4 bias : [0.83152698]

 Final Output is [0.77]
