In [1]:
import numpy as np

In [2]:
class Network:
    def __init__(self, layers):
        self.network = {}
        self.layers = layers
        
        for i in range(1, len(layers)):
            self.network[f"layer {i}"] = {
                "weights" : np.random.rand(
                layers[i-1], 
                layers[i]),
                "bias" : np.random.rand(
                layers[i])
            }
            
        
    def activation(self, values):
        """
            RELU activation function
        """
        relu = lambda x : max(0, x)
        
        return np.array([
            relu(value) for value in values
        ])
    
    def forward(self, input_layer):
        """
            outcome function which will give the output values output layer
            
            
            output = f(w.transpose * input + bias)
        """
        input_values = np.array(input_layer)
        
        for layer_name, layer in self.network.items():
            print(f"\n {layer_name} weights :", layer["weights"])
            print(f"\n {layer_name} bias :", layer["bias"])
            layer_output = (layer['weights'].transpose() @ input_values) + layer['bias']
            #print(f"\n {layer_name} Output :", layer_output)
            threshold_output = self.activation(layer_output)
            #print(f"\n {layer_name} Threshold_Output :", threshold_output)
            input_values = threshold_output
            
        return np.round(input_values, 2)
    

In [3]:
network = Network([5, 3, 2, 3, 1])
print(f"\nOutput is {network.forward([2, 1, 1 , 1, 2])}")


 layer 1 weights : [[0.09837394 0.12228406 0.35692309]
 [0.47813838 0.05604818 0.85518889]
 [0.40668365 0.07003841 0.15702005]
 [0.7163483  0.69014346 0.63515149]
 [0.19532325 0.378165   0.45608365]]

 layer 1 bias : [0.00126845 0.96712008 0.43208843]

 layer 2 weights : [[0.92558832 0.15205686]
 [0.94167333 0.69093469]
 [0.84316305 0.22253828]]

 layer 2 bias : [0.73375494 0.03683197]

 layer 3 weights : [[0.59505675 0.60798458 0.44971343]
 [0.68210714 0.76102403 0.31000006]]

 layer 3 bias : [0.97736456 0.47109285 0.59269615]

 layer 4 weights : [[0.66076442]
 [0.77619298]
 [0.27977629]]

 layer 4 bias : [0.67558079]

Output is [13.8]
